version: "3"
services:

  webapp:
    image: rps-veikkoni/web-app:2.0
    container_name: rps-veikkoni-web-app
    build: ./client/
    ports:
      - "3000:80"
  
  backend:
    image: rps-veikkoni/backend:1.0
    container_name: rps-veikkoni-backend
    build: ./backend/
    ports:
      - "5000:5000"

#  proxy:
#    image: sourabh385/cors-anywhere
#    container_name: rps-veikkoni-proxy
#    ports:
#      - "5005:5000"
